plugins {
    id 'java'
}

group = 'org.mentalizr'
version = '0.0.1-SNAPSHOT'

repositories {
    maven { url = "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
    mavenCentral()
}

dependencies {
    implementation libs.ap.utils.io
    testImplementation libs.ap.utils.core
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.engine
}

test {
    useJUnitPlatform()
}